#!/usr/bin/env python3
"""
Task 6: Multi-User Load Testing
Benchmark vLLM throughput and latency under concurrent user load.
"""

import os
import sys
import time
import json
import asyncio
import aiohttp

# TODO 1: Define concurrent user counts to test
CONCURRENT_USERS = [1, 5, 10, 20]  # TODO: Set to [1, 5, 10, 20]
URL = "http://localhost:8000/v1/completions"
MODEL = "HuggingFaceTB/SmolLM-135M"
PROMPT = "Write a short poem about coding."
MAX_TOKENS = 30

async def send_request(session):
    payload = {
        "model": MODEL,
        "prompt": PROMPT,
        "max_tokens": MAX_TOKENS,
        "temperature": 0.7
    }
    start = time.time()
    try:
        async with session.post(URL, json=payload) as response:
            if response.status == 200:
                data = await response.json()
                latency = time.time() - start
                tokens = data.get("usage", {}).get("completion_tokens", 0)
                return {"latency": latency, "tokens": tokens, "success": True}
            else:
                return {"latency": 0, "tokens": 0, "success": False}
    except Exception as e:
        return {"latency": 0, "tokens": 0, "success": False}

async def benchmark_concurrency(users):
    print(f"Running benchmark with {users} concurrent user(s)...")
    async with aiohttp.ClientSession() as session:
        # Create 'users' concurrent requests
        tasks = [send_request(session) for _ in range(users)]
        start_time = time.time()
        results = await asyncio.gather(*tasks)
        total_time = time.time() - start_time
        
        # Calculate metrics
        success_results = [r for r in results if r["success"]]
        total_tokens = sum(r["tokens"] for r in success_results)
        
        # TODO 2: Calculate throughput (tokens per second) under load
        # Hint: Divide total tokens generated by total elapsed time
        throughput = total_tokens / total_time if total_time > 0 else 0
        avg_latency = sum(r["latency"] for r in success_results) / len(success_results) if success_results else 0
        
        print(f"  Completed: {len(success_results)}/{users} successful requests")
        print(f"  Total time: {total_time:.2f} seconds")
        print(f"  Total tokens: {total_tokens}")
        print(f"  Throughput: {throughput:.1f} tok/s")
        print(f"  Average Latency: {avg_latency:.2f} seconds\n")
        
        return {
            "users": users,
            "throughput": round(throughput, 2),
            "latency": round(avg_latency, 2),
            "total_tokens": total_tokens,
            "total_time": round(total_time, 2)
        }

async def main_async():
    print("=" * 65)
    print("Task 6: Multi-User Load Testing")
    print("=" * 65)
    print(f"Target URL: {URL}")
    print(f"Model: {MODEL}")
    print("-" * 65 + "\n")

    results = []
    for users in CONCURRENT_USERS:
        res = await benchmark_concurrency(users)
        results.append(res)
        # Sleep brief period between tests to let server settle
        await asyncio.sleep(2)

    # Save results to markers directory
    os.makedirs("./markers", exist_ok=True)
    with open("./markers/load_test_results.json", "w") as f:
        json.dump(results, f, indent=2)

    # Write completion marker
    with open("./markers/task6_complete.txt", "w") as f:
        f.write("TASK_6_COMPLETE\n")

    print("Task 6 Complete!")
    print("Metrics saved to ./markers/load_test_results.json")
    print("Next: python task_7_tuning.py")

def main():
    asyncio.run(main_async())

if __name__ == "__main__":
    main()
